#static: /
web: npm run serve
cron: 37 * * * * ./analytics
# wsgi: dotted.module:entry_point
# release: make PROD=1
# cron: */5 * * * * python batch.py
# somepyworker: python somescript.py
# somenodeworker: node somescript.js
